version: 2
jobs:
  build:
    docker:
      - image: node
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    steps:
      - checkout
      - run:
              name: build project
              command: |
                      npm install
                      npm run export
                      cp CNAME __sapper__/export/CNAME
                      cp -r .circleci/ __sapper__/export/.circleci/
      - persist_to_workspace: 
              root: __sapper__
              paths: export/*
 
deploy:
  docker:
    - image: node
  steps:
    - checkout
    - attach_workspace:
        at: __sapper__
    - add_ssh_keys:
        fingerprints:
          - '46:85:46:1c:b4:a9:cd:28:9d:34:ee:f1:44:cb:d7:b3'
    - run:
        name: install gh-pages npm package
        command: |
          npm install -g --silent gh-pages
          git config user.email "Lyndogwin@projectpseudonym.co"
          git config user.name "Lyndogwin"
    - run:
        Name: Deploy static site to gh-pages branch
        command: gh-pages -t --dist __sapper__/export/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
